mutation userSignupVerification($verificationToken: String!) {
  verifySignUp(arg: { verificationToken: $verificationToken }) {
    message
    userLogIn {
      accessToken
      refreshToken
    }
  }
}
