#import "./event-preview-fields.fragment.gql"

query getEventByLocation(
  $lat: numeric!
  $long: numeric!
  $offset: Int
  $limit: Int
  $orderBy: [EventsOrderBy!]
  $cityId: UuidComparisonExp
  $date: TimestamptzComparisonExp
  $price: NumericComparisonExp
  $search: String
) {
  eventsByLocation(
    args: { lat: $lat, long: $long }
    limit: $limit
    offset: $offset
    orderBy: $orderBy
    where: {
      cityId: $cityId
      date: $date
      price: $price
      _or: [
        { tags: { _cast: { String: { _ilike: $search } } } }
        { title: { _ilike: $search } }
        { description: { _ilike: $search } }
      ]
    }
  ) {
    ...eventPreviewFields
  }
}
