# syntax=docker/dockerfile:1

FROM golang:1.19 AS build-stage

WORKDIR /app
RUN mkdir bin

COPY go.mod go.sum ./
RUN go mod download

COPY . .
# RUN ls
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/actions_go ./src

FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /
COPY --from=build-stage /bin/actions_go /actions_go

EXPOSE 8080
USER nonroot:nonroot

ENTRYPOINT ["/actions_go"]